{
 "title": "Cluster Health (Potent Pi Cluster)",
 "description": "This dashboard provides real-time and historical insights into the health and performance of the 5 Raspberry Pi nodes in the homelab cluster. It visualizes key hardware metrics to detect potential issues, optimize performance, and ensure system stability.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Potent Pi 1 - Odin",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"} / node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\"} / node_filesystem_avail_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\",instance=\"nodeexporter:9100\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\",instance=\"nodeexporter:9100\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 2 - Mimir",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"} / node_memory_MemTotal_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",mountpoint=\"/\"} / node_filesystem_avail_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 3 - Loki",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 4 - Skadi",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 5 - Frigg",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"} / node_memory_MemTotal_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", mountpoint=\"/\"} / node_filesystem_avail_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", device=\"end0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", device=\"end0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 1  (Odin) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"} - node_memory_MemAvailable_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 4 (Skadi) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Skadi)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"} - node_memory_MemAvailable_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"svr-mimir.asgard.onyxnet.lan:9100\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Skadi) - Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"svr-mimir.asgard.onyxnet.lan:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Skadi) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\", instance=\"nodeexporter:9100\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\", instance=\"nodeexporter:9100\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"svr-mimir.asgard.onyxnet.lan:9100\",device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Skadi) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\",device=\"end0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"svr-frigg.jotunheim.onyxnet.lan:9100\",device=\"end0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  }
 ]
}