{
 "title": "Homelab Node (Vanir NUC)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vanir Cluster - CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"} * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Vanir-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_node_info{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Vanir Cluster - MEM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"} / pve_memory_size_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"} / pve_disk_size_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Read/Write (I/O)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_read_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}",
     "legendFormat": "Read {{id}}"
    },
    {
     "expr": "pve_disk_write_bytes{instance=\"svr-vanir1.asgard.onyxnet.lan:9221\"}",
     "legendFormat": "Write {{id}}"
    }
   ]
  },
  {
   "title": "Receive (I/O)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes{instance=\"svr-aesir1.asgard.onyxnet.lan:9221\"}[5m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Transmit (I/O)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_transmit_bytes{instance=\"svr-aesir1.asgard.onyxnet.lan:9221\"}[5m])",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}