{
 "title": "24h Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Router & Potent Pis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router - Basic Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{job=\"prometheus-router\",mode=\"idle\"}[5m])) by (instance))",
     "legendFormat": "CPU Usage (%)"
    },
    {
     "expr": "100 * (node_memory_size_bytes{job=\"prometheus-router\"} - (node_memory_free_bytes{job=\"prometheus-router\"} + node_memory_buffer_bytes{job=\"prometheus-router\"} + node_memory_cache_bytes{job=\"prometheus-router\"} + node_memory_inactive_bytes{job=\"prometheus-router\"} + node_memory_laundry_bytes{job=\"prometheus-router\"})) / node_memory_size_bytes{job=\"prometheus-router\"}",
     "legendFormat": "MEM Usage (%)"
    },
    {
     "expr": "100 * (node_filesystem_size_bytes{job=\"prometheus-router\",mountpoint=\"/\"} - node_filesystem_free_bytes{job=\"prometheus-router\",mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"prometheus-router\",mountpoint=\"/\"}",
     "legendFormat": "Disk Usage (%)"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re0\"}[10m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization (1Gb Link)"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization (1Gb Link)"
    }
   ]
  },
  {
   "title": "Potent Pi 1 - Odin",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"} / node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\"} / node_filesystem_avail_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\",instance=\"nodeexporter:9100\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\",instance=\"nodeexporter:9100\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 2 - Mimir",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"nodeexp\"} / node_memory_MemTotal_bytes{job=\"nodeexp\"}))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nodeexp\",mountpoint=\"/\"} / node_filesystem_avail_bytes{job=\"nodeexp\",mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 3 - Loki",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 4 - Midgard",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 5 - Frigg",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"homeassistant\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"homeassistant\"} / node_memory_MemTotal_bytes{job=\"homeassistant\"}))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"homeassistant\", mountpoint=\"/\"} / node_filesystem_avail_bytes{job=\"homeassistant\", mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 1  (Odin) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexp\"} - node_memory_MemAvailable_bytes{job=\"nodeexp\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexp\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexp\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"nodeexp\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"nodeexp\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"homeassistant\"} - node_memory_MemAvailable_bytes{job=\"homeassistant\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"homeassistant\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"homeassistant\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"homeassistant\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"homeassistant\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Router - Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus-router\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"prometheus-router\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"prometheus-router\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Router - Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"prometheus-router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"nodeexp\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"homeassistant\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"nodeexp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"homeassistant\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}