{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{job=\"speedtest\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{job=\"speedtest\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Server ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{job=\"speedtest\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}