{
 "title": "PfSense Router",
 "description": "This dashboard provides a comprehensive view of the performance and activity of your pfSense router. Designed with multiple VLANs in mind, it monitors key metrics like network traffic, interface status, CPU and memory usage, and firewall events. Each VLAN is tracked individually to provide insights into traffic patterns, device behavior, and bandwidth utilization.\n\nKey Features:\n\nReal-time and historical data visualization for all VLANs\nTraffic analysis by VLAN and interface\nFirewall logs and alerts\nResource usage (CPU, memory, disk)\nWAN connection performance and latency monitoring",
 "tags": [
  "System Performance",
  "Traffic Analysis",
  "Bandwidth",
  "Metrics",
  "Firewall",
  "Dashboard",
  "Monitoring",
  "Networking",
  "VLAN",
  "Router",
  "pfSense"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"prometheus-router\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(1 - (node_memory_free_bytes{job=\"prometheus-router\"} / node_memory_size_bytes{job=\"prometheus-router\"})) * 100",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=\"/\",job=\"prometheus-router\"} / node_filesystem_size_bytes{mountpoint=\"/\",job=\"prometheus-router\"})) * 100",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re0\"}[5m]) * 8) / 1000000000 * 100",
     "legendFormat": "Network Utilization (Incoming)"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1\"}[5m]) * 8) / 1000000000 * 100",
     "legendFormat": "Network Utilization (Outgoing)"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"prometheus-router\"} - node_memory_free_bytes{job=\"prometheus-router\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_size_bytes{job=\"prometheus-router\"} - (node_memory_size_bytes{job=\"prometheus-router\"} - node_memory_free_bytes{job=\"prometheus-router\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus-router\"}",
     "legendFormat": "Load Avererage (1min)"
    },
    {
     "expr": "node_load5{job=\"prometheus-router\"}",
     "legendFormat": "Load Average (5min)"
    },
    {
     "expr": "node_load15{job=\"prometheus-router\"}",
     "legendFormat": "Load Average (15min)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"prometheus-router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLAN Throughput (Incoming)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.10\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 10)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.25\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 25)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.50\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 50)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.99\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 99)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.100\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 100)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re1.1000\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 1000)"
    }
   ]
  },
  {
   "title": "WAN Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\", device=\"re0\"}[1m]) * 8",
     "legendFormat": "Incoming Bandwidth (WAN)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\", device=\"re1\"}[1m]) * 8",
     "legendFormat": "Outgoing Bandwidth (WAN)"
    }
   ]
  },
  {
   "title": "VLAN Throughput (Outgoing)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.10\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 10)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.25\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 25)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.50\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 50)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.99\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 99)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.100\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 100)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.1000\"}[1m]) * 8",
     "legendFormat": "Outgoing (VLAN 1000)"
    }
   ]
  }
 ]
}