# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # or "icmp"
    static_configs:
      - targets:
        - https://google.com
        - https://github.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # blackbox exporter address
  
  - job_name: 'blackbox-icmp'
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /probe
    params:
      module: [icmp_ping]
    static_configs:
      - targets:
          - google.com
          - github.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
  
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8081'
  
  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 60m
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 'speedtest-exporter:9798'

  - job_name: 'prometheus-router'
    static_configs:
      - targets:
        - '10.100.0.1:9100'

  - job_name: 'homeassistant'
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets:
        - 'svr-frigg.jotunheim.onyxnet.lan:9100'

  - job_name: 'pihole_main'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'svr-odin.asgard.onyxnet.lan:9617'

  - job_name: 'pihole_backup'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'svr-forseti.asgard.onyxnet.lan:9617'

  - job_name: 'nodeexp'
    static_configs:
      - targets:
        - 'svr-mimir.asgard.onyxnet.lan:9100'

  - job_name: 'pve-aesir'
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    static_configs:
      - targets:
        - 'svr-aesir1.asgard.onyxnet.lan:9221'
        - 'svr-aesir2.asgard.onyxnet.lan:9221'
        - 'svr-aesir3.asgard.onyxnet.lan:9221'

  - job_name: 'pve-vanir'
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    static_configs:
      - targets:
        - 'svr-vanir1.asgard.onyxnet.lan:9221'
        - 'svr-vanir2.asgard.onyxnet.lan:9221'
        - 'svr-vanir3.asgard.onyxnet.lan:9221'
